version: '3.8'

services:
  mobile:
    build:
      context: .
      target: development
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    environment:
      - NODE_ENV=development
      - EXPO_PUBLIC_API_URL=http://localhost:5000
      - EXPO_PUBLIC_GOOGLE_MAPS_API_KEY=your-google-maps-api-key
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - eventconnect-mobile-network
    restart: unless-stopped
    tty: true
    stdin_open: true

networks:
  eventconnect-mobile-network:
    driver: bridge